services:
  master:
    container_name: master_DB
    image: mysql:5.6
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    volumes:
      - ./dbsetting:/etc/mysql/mysql.conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8001:3306"

  sub:
    container_name: sub_DB
    image: mysql:5.6
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    volumes:
      - ./dbsetting:/etc/mysql/mysql.conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8002:3306"